In [12]:
import numpy as np

In [13]:
vet = np.array([1,2,3,6,8,9,10,11,13,15,101,15,13,12,3,1])
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  13,  15, 101,  15,  13,
        12,   3,   1])

In [14]:
type(vet)

numpy.ndarray

In [16]:
vet2 = np.array([1,2,3,4,5,])
vet2.cumsum()

array([ 1,  3,  6, 10, 15])

In [20]:
print(vet[4])

8


In [21]:
vet[8]=-1
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  -1,  15, 101,  15,  13,
        12,   3,   1])

In [23]:
vet=np.append(vet,202)
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  -1,  15, 101,  15,  13,
        12,   3,   1, 202, 202])

In [26]:
vet=vet[:-1]
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  -1,  15, 101,  15,  13,
        12,   3])

In [29]:
vetor2x3=np.array([[1,2,3],[4,5,6]])
vetor2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
vetor2x3.shape

(2, 3)

In [32]:
vetor3x2=np.array([[1,2],[3,4],[5,6]])
vetor3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
vetor3x2.shape

(3, 2)

In [37]:
unicos_vet=np.unique(vet)
unicos_vet

array([ -1,   1,   2,   3,   6,   8,   9,  10,  11,  12,  13,  15, 101])

In [38]:
idades = np.array([44,45,23,23,28,19,20,19,17,51,29,28,31,32])
mediaIA2 = round(idades.mean(),3)
mediaIA2

np.float64(29.214)

In [43]:
j = np.unique(idades)
j

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])